site_name: "Boomerang Documentation"
site_url: https://secure-software-engineering.github.io/Boomerang/
repo_url: https://github.com/secure-software-engineering/Boomerang/
edit_uri: edit/develop/docs/

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - First Steps: getting-started.md
      - Example Analyses: examples.md

theme:
  name: material
  logo: ./img/SparseBoomerangLogo.png
#  favicon: ./img/icon.png
  palette:
    primary: blue
  features:
    - navigation.sections

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.tabbed:
      alternate_style: true

extra:
  version:
    provider: mike
