name: Branch Documentation Snapshot

permissions:
  pages: write
  deployments: write
  contents: write

on:
  push:
    branches:
      - main
      - develop

    paths:
      - 'mkdocs.yml'
      - 'docs/**'
      - '.github/workflows/deploy-branch-snapshot.yml'

concurrency: pages

jobs:
  deploy-snapshot:
    uses: secure-software-engineering/actions/.github/workflows/documentation-workflows/pages-branch-snapshot.yml@develop
    with:
      latest_branch: develop
      version: "maven"