name: PR Documentation Preview

permissions:
  pages: write
  deployments: write
  contents: write
  pull-requests: write

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize
      - reopened
  paths:
    - 'mkdocs.yml'
    - 'docs/**'
    - '.github/workflows/deploy-pr-preview.yml'

concurrency: pages

jobs:
  deploy-preview:
    uses: secure-software-engineering/actions/.github/workflows/pages-pr-preview.yml@Change evelop
    with:
      enable_comment: true
      title_prefix: "Boomerang PR Preview: "