name: PR Documentation Preview

permissions:
  pages: write
  deployments: write
  contents: write
  pull-requests: write

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize
      - reopened
    paths:
      - 'mkdocs.yml'
      - 'docs/**'
      - 'documentation-pr-preview.yml'

concurrency: pages

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    name: Deploy Documentation Preview
    steps:
      - name: sad
        uses: secure-software-engineering/actions/documentation/handle-pr-preview@develop
        with:
          enable_comment: true
          name: ${{ github.base_ref }}
          title: "Boomerang PR Preview: "
