name: Deploy Documentation

permissions:
  pages: write
  deployments: write
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'mkdocs.yml'
      - 'docs/**'
      - '.github/worklflows/gh-pages.yml'
    pull_request_target:
      types:
        - opened
        - reopened
        - synchronize
        - closed
      paths:
        - 'mkdocs.yml'
        - 'docs/**'
        - '.github/workflows/gh-pages.yml'
concurrency: pages

jobs:
  deploy:
    uses: secure-software-engineering/actions/gh-pages.yml@roshansamantaray-patch-1
    with:
      workflow_name: "Deploy Boomerang Documentation"
      deploy_branch: ${{ github.ref_name }}
