name: Java CI with Maven

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  BuildAndTest:
    strategy:
      fail-fast: false
      matrix:
        framework: [Soot, SootUp, Opal]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
          distribution: adopt
          java-package: jdk
          java-version: 11
    - name: Build with Maven
      run: mvn -B clean verify -DtestSetup=${{ matrix.framework }}
